#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate shared FPGA platform contract constants (C/SV/Python).")
    ap.add_argument(
        "--contract",
        type=Path,
        default=Path("docs/bringup/contracts/fpga_platform_contract.json"),
        help="Path to contract JSON (default: docs/bringup/contracts/fpga_platform_contract.json)",
    )
    ap.add_argument("--out-dir", type=Path, default=Path("tools/generated"))
    args = ap.parse_args()

    contract_path = args.contract
    data = json.loads(contract_path.read_text(encoding="utf-8"))

    def parse_int(x: str) -> int:
        return int(x, 0)

    uart_base = parse_int(data["uart_mmio_base"])
    exit_addr = parse_int(data["exit_mmio_addr"])
    boot_pc = parse_int(data["boot_pc_default"])
    boot_sp = parse_int(data["boot_sp_default"])

    out_dir: Path = args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    (out_dir / "linx_fpga_platform_contract.h").write_text(
        "\n".join(
            [
                "#pragma once",
                "",
                "// Generated by tools/gen_fpga_platform_contract.py",
                "",
                "#include <stdint.h>",
                "",
                f"#define LINX_FPGA_UART_MMIO_BASE UINT64_C(0x{uart_base:016x})",
                f"#define LINX_FPGA_EXIT_MMIO_ADDR UINT64_C(0x{exit_addr:016x})",
                f"#define LINX_FPGA_BOOT_PC_DEFAULT UINT64_C(0x{boot_pc:016x})",
                f"#define LINX_FPGA_BOOT_SP_DEFAULT UINT64_C(0x{boot_sp:016x})",
                "",
            ]
        ),
        encoding="utf-8",
    )

    (out_dir / "linx_fpga_platform_contract.svh").write_text(
        "\n".join(
            [
                "// Generated by tools/gen_fpga_platform_contract.py",
                "",
                f"`define LINX_FPGA_UART_MMIO_BASE 64'h{uart_base:016x}",
                f"`define LINX_FPGA_EXIT_MMIO_ADDR 64'h{exit_addr:016x}",
                f"`define LINX_FPGA_BOOT_PC_DEFAULT 64'h{boot_pc:016x}",
                f"`define LINX_FPGA_BOOT_SP_DEFAULT 64'h{boot_sp:016x}",
                "",
            ]
        ),
        encoding="utf-8",
    )

    (out_dir / "linx_fpga_platform_contract.py").write_text(
        "\n".join(
            [
                "# Generated by tools/gen_fpga_platform_contract.py",
                "",
                f"UART_MMIO_BASE = 0x{uart_base:016x}",
                f"EXIT_MMIO_ADDR = 0x{exit_addr:016x}",
                f"BOOT_PC_DEFAULT = 0x{boot_pc:016x}",
                f"BOOT_SP_DEFAULT = 0x{boot_sp:016x}",
                "",
            ]
        ),
        encoding="utf-8",
    )

    print(out_dir / "linx_fpga_platform_contract.h")
    print(out_dir / "linx_fpga_platform_contract.svh")
    print(out_dir / "linx_fpga_platform_contract.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

